markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://cainelli.me
keep_files: ["v1.0"]
compose_current: 1.14.0

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: cainelli
      enginebranch: 1.13.x
      toc_min: 2
      toc_max: 3
      tree: true


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
